#!/usr/bin/env python3
import asyncio

try:
    from matrix_reminder_bot import main

    # Run the main function of the bot
    asyncio.get_event_loop().run_until_complete(main.main())
except ImportError:
    print("Unable to import matrix_reminder_bot.main")
